/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bookshop.gui;

import com.bookshop.util.BinarySearchTree;
import javax.swing.JOptionPane;

/**
 *
 * @author amila
 */
public class RemoveWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoveWindow
     */
     
    public String bookIdentifier; //used to assign the name of the book for particular ISBNte
    private BinarySearchTree searchTree;
    
    //no args constructor
    public RemoveWindow() {
        initComponents();
       // bookIdentifier = "test1 value"; 
        setTitle("Remove Book");
    }
    //overloaded constructor
    public RemoveWindow(BinarySearchTree bst) {
        initComponents();
       // bookIdentifier = "test1 value"; 
        setTitle("Remove Book");
        searchTree = bst;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbRemoveType = new javax.swing.JComboBox();
        txtRemoveValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRemoveBook = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Delete By Using");

        cmbRemoveType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Book Title" }));

        jLabel2.setText("ISBN/Book Title");

        btnRemoveBook.setText("Remove");
        btnRemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRemoveValue)
                            .addComponent(cmbRemoveType, 0, 163, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRemoveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRemoveValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(72, 72, 72)
                .addComponent(btnRemoveBook)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBookActionPerformed
    
    if(cmbRemoveType.getSelectedItem().toString().equals("ISBN")){
    
        //To Xcoders  :- search the book name for the particular ISBN and assign it to bookidentifier variable
    
    }
    else{
    
        bookIdentifier = txtRemoveValue.getText();
    
    }
        
   if (txtRemoveValue.getText().equals("")){ 
       
       JOptionPane.showMessageDialog(null,"Please Enter ISBN/Book Title");
   } 
   else{
       
        
        // first ask confirmation to delete the particular book through confirmation dialogue
       int reply = JOptionPane.showConfirmDialog(null,"Are you want to delete " +bookIdentifier+" ?","Confirmation",JOptionPane.OK_CANCEL_OPTION);
       
       if(reply == JOptionPane.OK_OPTION){
          //******** if user reply is OK...then remove the book 
           
            //To Xcoders  :- write code to remove Book from database here:
           
           
       JOptionPane.showMessageDialog(null, "Book remove successfully!");
       
       
       
       }
       
       }
    }//GEN-LAST:event_btnRemoveBookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveBook;
    private javax.swing.JComboBox cmbRemoveType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRemoveValue;
    // End of variables declaration//GEN-END:variables
}
